eureka:
  client:
    service-url:
      defaultZone: http://120.79.225.94:8901/eureka/
  instance:
    instance-id: email-server
    prefer-ip-address: true

spring:
  mail:
    host: smtp.163.com
    username: zouxazk@163.com
    password: zxa123456
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    enabled: true
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/ # 模板存放在资源目录的 templates/ 文件下
    suffix: .html # 模板后缀
    check-template-location: true
    check-template: false
    cache: false # 调试时关闭缓存

mail:
  from:
    address: zouxazk@163.com
  binding:
    time: 10




info:
  appName: mySpringCloud
  author: zxa
  lalala: lalala

