spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka/,http://localhost:8902/eureka/


